package main

import (
  "fmt"
  "bytes"
)

func main()  {

  var text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras interdum mi eu magna fermentum, vel luctus tellus semper. Nunc dignissim eleifend ipsum, nec viverra mauris pellentesque non. Fusce auctor ex id mauris egestas, quis luctus nunc pharetra. Sed in dignissim nisi. Aliquam sed tempor urna, nec aliquam mi. Aenean eu feugiat lacus, vel dictum eros. Nulla condimentum porttitor aliquet. Vestibulum vehicula elit non arcu auctor maximus. Quisque est eros, maximus nec diam faucibus, mollis odio."

  checkA := bytes.Count([]byte(text), []byte{'A'})
  checka := bytes.Count([]byte(text), []byte{'a'})
  checkB := bytes.Count([]byte(text), []byte{'B'})
  checkb := bytes.Count([]byte(text), []byte{'b'})
  checkC := bytes.Count([]byte(text), []byte{'C'})
  checkc := bytes.Count([]byte(text), []byte{'c'})
  checkD := bytes.Count([]byte(text), []byte{'D'})
  checkd := bytes.Count([]byte(text), []byte{'d'})
  checkE := bytes.Count([]byte(text), []byte{'E'})
  checke := bytes.Count([]byte(text), []byte{'e'})
  checkF := bytes.Count([]byte(text), []byte{'F'})
  checkf := bytes.Count([]byte(text), []byte{'f'})
  checkG := bytes.Count([]byte(text), []byte{'G'})
  checkg := bytes.Count([]byte(text), []byte{'g'})
  checkH := bytes.Count([]byte(text), []byte{'H'})
  checkh := bytes.Count([]byte(text), []byte{'h'})
  checkI := bytes.Count([]byte(text), []byte{'I'})
  checki := bytes.Count([]byte(text), []byte{'i'})
  checkJ := bytes.Count([]byte(text), []byte{'J'})
  checkj := bytes.Count([]byte(text), []byte{'j'})
  // checkf := bytes.Count([]byte(text), []byte{'K'})
  // checkf := bytes.Count([]byte(text), []byte{'k'})
  // checkf := bytes.Count([]byte(text), []byte{'L'})
  // checkf := bytes.Count([]byte(text), []byte{'l'})
  // checkf := bytes.Count([]byte(text), []byte{'M'})
  // checkf := bytes.Count([]byte(text), []byte{'m'})
  // checkf := bytes.Count([]byte(text), []byte{'N'})
  // checkf := bytes.Count([]byte(text), []byte{'n'})
  // checkf := bytes.Count([]byte(text), []byte{'O'})
  // checkf := bytes.Count([]byte(text), []byte{'o'})
  // checkf := bytes.Count([]byte(text), []byte{'P'})
  // checkf := bytes.Count([]byte(text), []byte{'p'})
  // checkf := bytes.Count([]byte(text), []byte{'Q'})
  // checkf := bytes.Count([]byte(text), []byte{'q'})
  // checkf := bytes.Count([]byte(text), []byte{'R'})
  // checkf := bytes.Count([]byte(text), []byte{'r'})
  // checkf := bytes.Count([]byte(text), []byte{'S'})
  // checkf := bytes.Count([]byte(text), []byte{'s'})
  // checkf := bytes.Count([]byte(text), []byte{'T'})
  // checkf := bytes.Count([]byte(text), []byte{'t'})
  // checkf := bytes.Count([]byte(text), []byte{'U'})
  // checkf := bytes.Count([]byte(text), []byte{'u'})

  fmt.Println("karakter A sebanyak: ",checkA)
  fmt.Println("karakter a sebanyak: ",checka)
  fmt.Println("karakter B sebanyak: ",checkB)
  fmt.Println("karakter b sebanyak: ",checkb)
  fmt.Println("karakter C sebanyak: ",checkC)
  fmt.Println("karakter c sebanyak: ",checkc)
  fmt.Println("karakter D sebanyak: ",checkD)
  fmt.Println("karakter d sebanyak: ",checkd)
  fmt.Println("karakter E sebanyak: ",checkE)
  fmt.Println("karakter e sebanyak: ",checke)
  fmt.Println("karakter F sebanyak: ",checkF)
  fmt.Println("karakter f sebanyak: ",checkf)
  fmt.Println("karakter G sebanyak: ",checkG)
  fmt.Println("karakter g sebanyak: ",checkg)
  fmt.Println("karakter H sebanyak: ",checkH)
  fmt.Println("karakter h sebanyak: ",checkh)
  fmt.Println("karakter I sebanyak: ",checkI)
  fmt.Println("karakter i sebanyak: ",checki)
  fmt.Println("karakter J sebanyak: ",checkJ)
  fmt.Println("karakter j sebanyak: ",checkj)

}
